### ISSUE TITLE
Issues with outputs capture (AssertionError: feed_data after feed_eof)

### ISSUE THREAD

**Issue by AntoninG** [PrefectHQ/prefect-dbt#146]
# Bug summary
When using `prefect_shell.ShellOperation` or `prefect_dbt.DbtCoreOperation` to run dbt commands, the subprocess seems unable to capture properly the command outputs. 

This is non blocking as the dbt commands seems to run properly up to the end, but it generates a lot of ERROR-level logs and it seems to prevent me from getting the output as the `fetch_result()` always returns an empty list even though the ERROR logs generated make the dbt logs recognizable as you will see further down this issue. 

# Reproduction
## Dependencies
```
Using python 3.8.10

[tool.poetry.dependencies]
aeye = "0.158.0.dev1"
alembic = "^1.8.1"
dbt-bigquery = "1.5.0"
dbt-core = "1.5.0"
prefect = "2.10.9"
psycopg2-binary = "~=2.9.2"
prefect-dbt = {version = "~=0.3", extras = ["cli", "bigquery"]}
python-slugify = "^8.0.1"
```

## Task snippet
```
dbt_operation_kwargs = dict(
    commands=["dbt --no-use-colors run --target ci"],
    stream_output=True,
    env={
        "DBT_PROFILES_DIR": ".",
        "GOOGLE_APPLICATION_CREDENTIALS": GOOGLE_APPLICATION_CREDENTIALS,
        "DBT_CI_DATASET": TESTS_DATASET_NAME,
    },
)

@task(name="tests_create_dataset", persist_result=True)
def dbt_task() -> ShellProcess:
    with DbtCoreOperation(**dbt_operation_kwargs) as dbt_operation:
        dbt_process: ShellProcess = dbt_operation.trigger()
        try:
            dbt_process.wait_for_completion()
        except RuntimeError as exc:
            raise RuntimeError(dbt_process.fetch_result()) from exc
        return dbt_process

@flow
def main_flow():
    return dbt_task().submit()
```

## Results
```
...
17:23:15.522 | ERROR   | asyncio - Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'15:23:15   ...n15:23:15  \n')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'15:23:15   ...n15:23:15  \n')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 95, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/subprocess.py", line 69, in pipe_data_received
    reader.feed_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
17:23:15.525 | ERROR   | asyncio - Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'15:23:15  D...P=0 TOTAL=8\n')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'15:23:15  D...P=0 TOTAL=8\n')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 95, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/subprocess.py", line 69, in pipe_data_received
    reader.feed_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
...
```

# Workaround tested
- Use `dbt-core~=1.3` and `dbt-bigquery~=1.3` as said in this issue: #120 => did not work
- Remove `colorama` package as proposed in this issue: https://github.com/PrefectHQ/prefect/issues/6335 => did not work as this was a dependency of dbt-core

It seems other people on #120 are encountering the same problem.

Thanks for your help!

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-dbt/#contributing) a pull request to resolve this!

**Comment by giacomochiarella** [comment]
same issue here

**Comment by desertaxle** [comment]
We are investigating a fix for this issue, but we've observed that this bug only affects `DbtCoreOperation` and `ShellOperation` when used in a synchronous context when using `.trigger()`, `.wait_for_completion()`, and `.fetch_results()` in succession. Using the `.run()` method will allow you to retrieve the output of shell operations while we continue to investigate this issue.

**Comment by AntoninG** [comment]
I am going to test this! Thanks

**Comment by AntoninG** [comment]
Hmmm, I will have an issue with this solution. If I am reading correctly, by using run() I have no way to get the outputs if the `return_code != 0` as the `wait_for_completion` is not caught and the `ShellProcess` object is not returned, am I not?

**Comment by giacomochiarella** [comment]
I'm not fully convinced about this solution. Looking at the run() method, the only difference I see from my code is running wait and fetch under:
`async with open_process(**input_open_kwargs) as process:`
I would say then the only workaround here is to fully reproduce the run method where you need maybe
