### ISSUE TITLE
`ValueError`: The keyword, `_is_anonymous`, has already been provided in `TargetConfigs`

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect-dbt#59]
`_is_anonymous` is being included in the result of `_populate_configs_json` which makes it possible that other block metadata fields are also being included. Block metadata fields shouldn't be included in dbt profiles generated by this collection.

Full stacktrace of the error:
```
14:07:11.533 | ERROR   | Task run 'trigger_dbt_cli_command-321ca940-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/d.hinnenkamp/Desktop/test-prefect/.venv/lib/python3.8/site-packages/prefect/engine.py", line 1185, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "/Users/d.hinnenkamp/Desktop/test-prefect/.venv/lib/python3.8/site-packages/prefect_dbt/cli/commands.py", line 136, in trigger_dbt_cli_command
    profile = dbt_cli_profile.get_profile()
  File "/Users/d.hinnenkamp/Desktop/test-prefect/.venv/lib/python3.8/site-packages/prefect_dbt/cli/credentials.py", line 107, in get_profile
    "outputs": {self.target: self.target_configs.get_configs()},
  File "/Users/d.hinnenkamp/Desktop/test-prefect/.venv/lib/python3.8/site-packages/prefect_dbt/cli/configs/snowflake.py", line 78, in get_configs
    configs_json = super().get_configs()
  File "/Users/d.hinnenkamp/Desktop/test-prefect/.venv/lib/python3.8/site-packages/prefect_dbt/cli/configs/base.py", line 53, in get_configs
    return self._populate_configs_json({}, self.dict())
  File "/Users/d.hinnenkamp/Desktop/test-prefect/.venv/lib/python3.8/site-packages/prefect_dbt/cli/configs/base.py", line 34, in _populate_configs_json
    configs_json = self._populate_configs_json(configs_json, value)
  File "/Users/d.hinnenkamp/Desktop/test-prefect/.venv/lib/python3.8/site-packages/prefect_dbt/cli/configs/base.py", line 37, in _populate_configs_json
    raise ValueError(
ValueError: The keyword, _is_anonymous, has already been provided in TargetConfigs; remove duplicated keywords to continue
```

Reproducible example:
```python
    snowflake_connector_block = await SnowflakeConnector.load("wld-snowflake-connection")
    connector = snowflake_connector_block
    target_configs = SnowflakeTargetConfigs(
        connector=connector
    )
    dbt_cli_profile = DbtCliProfile(
        name="profile_name",
        target="dev",
        target_configs=target_configs
    )
    debug = await trigger_dbt_cli_command.submit(
        "dbt debug",
        profiles_dir='profile',
        project_dir='wld-dbt-warehouse/dbt-project',
        overwrite_profiles=True,
        dbt_cli_profile=dbt_cli_profile,
        return_state=True
    )
```

Originally reported by @mcfuhrt in [Slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1662984634931949).

**Comment by jmg-duarte** [comment]
I am having the same issue with `block_type_slug`. I am also using a `SnowflakeTargetConfigs`, I followed the example from the `README` and don't define said variable anywhere.
