### ISSUE TITLE
`trigger_dbt_cli_command` not specifying PowerShell as shell in `shell_run_command` call

### ISSUE THREAD

**Issue by costructuralist** [PrefectHQ/prefect-dbt#87]
Running the following flow locally on Windows (from within a Poetry environment):

```
@flow
def dbt_flow():
    trigger_dbt_cli_command(command="dbt test", project_dir="""C:\Source\data\debut""")
```
gives the following error:
```
16:15:35.503 | INFO    | Task run 'trigger_dbt_cli_command-321ca940-0' - Running dbt command: dbt test --profiles-dir C:\Users\myusername\.dbt --project-dir C:\Source\data\debut
16:15:35.775 | ERROR   | Task run 'trigger_dbt_cli_command-321ca940-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Local\pypoetry\Cache\virtualenvs\prefect-etl-szksG6RR-py3.10\lib\site-packages\prefect\engine.py", line 1183, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "C:\Users\myusername\AppData\Local\pypoetry\Cache\virtualenvs\prefect-etl-szksG6RR-py3.10\lib\site-packages\prefect_dbt\cli\commands.py", line 158, in trigger_dbt_cli_command
    result = await shell_run_command.fn(command=command, **shell_run_command_kwargs)
  File "C:\Users\myusername\AppData\Local\pypoetry\Cache\virtualenvs\prefect-etl-szksG6RR-py3.10\lib\site-packages\prefect_shell\commands.py", line 96, in shell_run_command
    raise RuntimeError(msg)
RuntimeError: Command failed with exit code 127:
/bin/bash: C:UsersmyusernameAppDataLocalTempprefect-atmv4tpr: No such file or directory
```
Being on Windows, bash isn't available.

In `trigger_dbt_cli_command` the `shell` parameter of the `shell_run_command` call isn't passed, so that it defaults to `bash` when on Windows:
https://github.com/PrefectHQ/prefect-dbt/blob/e3ff884ec348aaf95b8dd842dd90bf7276011db4/prefect_dbt/cli/commands.py#L158

https://github.com/PrefectHQ/prefect-shell/blob/a75f4e5d6ef448f0aaf2747fdfd22a52ce04e676/prefect_shell/commands.py#L20

**Comment by costructuralist** [comment]
A workaround is to specify PowerShell in `shell_run_command_kwargs` for `trigger_dbt_cli_command`:

```
shell_run_command_kwargs = { "shell": "powershell" }
trigger_dbt_cli_command(command="dbt test", project_dir=dbt_project_path, **shell_run_command_kwargs)
```
